In [ ]:
from keras.models import Sequential, save_model
from keras.layers import Conv2D, MaxPool2D, MaxPooling2D, Dense, Dropout, Activation, Flatten
import keras.layers
import cv2 as cv
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import os

In [ ]:
train_X = []
train_y = []
for i in range(0,43):
    n = str(i)
    train_Path = "/content/drive/MyDrive/Sanket/GSTD/Train/" + n
    label = [0 for i in range(0, 43)]
    label[i] = 1
    for filename in os.listdir(train_Path):
        img = cv.imread(train_Path + "/" + filename)
        img = cv.resize(img, (32,32))
        print(filename)
        train_X.append(img)
        train_y.append(label)
train_X = np.asarray(train_X)
train_X = train_X/255
train_X = np.asarray(train_X, dtype = "float32")
train_y = np.asarray(train_y, dtype= "float32")

Streaming output truncated to the last 5000 lines.
00035_00033_00009.png
00035_00025_00020.png
00035_00002_00023.png
00035_00007_00025.png
00035_00000_00000.png
00035_00029_00026.png
00035_00038_00017.png
00035_00016_00024.png
00035_00017_00019.png
00035_00039_00001.png
00035_00011_00001.png
00035_00017_00016.png
00035_00015_00022.png
00035_00019_00021.png
00035_00022_00002.png
00035_00026_00016.png
00035_00008_00004.png
00035_00011_00010.png
00035_00006_00005.png
00035_00011_00007.png
00035_00028_00021.png
00035_00027_00022.png
00035_00024_00002.png
00035_00005_00018.png
00035_00020_00004.png
00035_00032_00023.png
00035_00012_00011.png
00035_00013_00006.png
00035_00000_00016.png
00035_00014_00029.png
00035_00020_00009.png
00035_00022_00021.png
00035_00007_00012.png
00035_00022_00019.png
00035_00018_00026.png
00035_00032_00001.png
00035_00014_00026.png
00035_00026_00010.png
00035_00023_00017.png
00035_00020_00029.png
00035_00000_00017.png
00035_00010_00018.png
00035_00015_00024.png
000

In [ ]:
counter = 0
test_X = []
test_y = []
test_Path = "/content/drive/MyDrive/Sanket/GSTD/Test"
for filename in os.listdir(test_Path):
        img = cv.imread(test_Path + "/" + filename)
        print(img)
        try:
          img = cv.resize(img, (32,32))
        except:
          continue
        label = [0 for i in range(0, 43)]
        #6 is the column # within the .CSV file        label[df.loc[counter][6]] = 1
        print(filename)
        test_X.append(img)
        test_y.append(label)
        counter += 1
test_X = np.asarray(test_X)
test_X = test_X/255
test_X = np.asarray(test_X, dtype = "float32")
test_y = np.asarray(test_y, dtype= "float32")

Streaming output truncated to the last 5000 lines.
[[[35 35 39]
  [37 35 38]
  [33 35 38]
  ...
  [32 33 25]
  [27 27 24]
  [27 29 30]]

 [[48 48 52]
  [42 37 40]
  [35 36 38]
  ...
  [34 33 30]
  [32 31 31]
  [29 30 34]]

 [[36 37 41]
  [42 40 43]
  [37 37 39]
  ...
  [27 27 28]
  [29 29 33]
  [34 34 41]]

 ...

 [[93 70 62]
  [89 66 63]
  [77 63 64]
  ...
  [36 37 51]
  [42 45 49]
  [41 41 36]]

 [[81 58 56]
  [87 65 64]
  [80 66 65]
  ...
  [37 37 49]
  [42 44 47]
  [39 40 34]]

 [[79 57 48]
  [79 58 50]
  [74 59 52]
  ...
  [37 37 44]
  [36 38 40]
  [37 39 37]]]
01690.png
[[[ 80  84  87]
  [ 76  81  83]
  [ 85  85  87]
  ...
  [ 49  54  60]
  [ 50  54  55]
  [ 53  57  54]]

 [[ 88  86  88]
  [ 84  85  89]
  [ 91  84  91]
  ...
  [ 44  49  55]
  [ 47  52  53]
  [ 48  55  53]]

 [[ 79  79  81]
  [ 84  87  94]
  [ 75  73  85]
  ...
  [ 47  50  56]
  [ 49  51  53]
  [ 52  55  53]]

 ...

 [[ 66  65  65]
  [ 70  64  63]
  [ 65  63  61]
  ...
  [ 55  54  64]
  [ 47  48  53]
  [ 55  50  5

In [ ]:
model = Sequential()
model.add(Conv2D(32, (3, 3), padding='same',
                 input_shape=train_X.shape[1:]))
model.add(Activation('relu'))
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Conv2D(64, (3, 3), padding='same'))
model.add(Activation('relu'))
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(392))
model.add(Activation('relu'))
model.add(Dropout(0.5))
model.add(Dense(43))
model.add(Activation('softmax'))

In [ ]:
from keras import optimizers

In [ ]:
import pandas as pd

In [ ]:
#opt = keras.optimizers.RMSprop(lr=0.0001, decay=1e-6)
#model.compile(loss='categorical_crossentropy',optimizer=opt,metrics=['accuracy'])
#history = model.fit(train_X, train_y, batch_size= 16, epochs= 6, validation_data= (test_X, test_y),shuffle=True)

In [ ]:
#optimizers = ['Adadelta', 'Adagrad', 'Adam', 'RMSprop', 'SGD']
optimizers = ['Adadelta']

for i in optimizers:
  opt = keras.optimizers.Adadelta(lr=0.1, decay=1e-6)
  model.compile(loss='categorical_crossentropy',optimizer=i,metrics=['accuracy'])
  hist=model.fit(train_X, train_y, batch_size= 64, epochs= 50, validation_data= (test_X, test_y),shuffle=True)

  train_loss = []
  test_loss = []
  train_acc = []
  test_acc = []

  train_loss = hist.history['loss']
  test_loss = hist.history['val_loss']
  train_acc = hist.history['accuracy']
  test_acc = hist.history['val_accuracy']


import pandas as pd
train_acc = pd.DataFrame (train_acc, columns = [i])
test_acc = pd.DataFrame (test_acc, columns = [i])
train_loss = pd.DataFrame (train_loss, columns = [i])
test_loss = pd.DataFrame (test_loss, columns = [i])


train_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_acc_64.csv', index=False)
test_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_acc_64.csv', index=False)
train_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_loss_64.csv', index=False)
test_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_loss_64.csv', index=False)



Epoch 1/50
615/615 [==============================] - 6s 8ms/step - loss: 0.0054 - accuracy: 0.9994 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 2/50
615/615 [==============================] - 5s 9ms/step - loss: 0.0046 - accuracy: 0.9996 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 3/50
615/615 [==============================] - 5s 9ms/step - loss: 0.0047 - accuracy: 0.9994 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 4/50
615/615 [==============================] - 5s 8ms/step - loss: 0.0047 - accuracy: 0.9994 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 5/50
615/615 [==============================] - 7s 11ms/step - loss: 0.0050 - accuracy: 0.9994 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 6/50
615/615 [==============================] - 6s 10ms/step - loss: 0.0047 - accuracy: 0.9994 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 7/50
615/615 [==============================] - 6s 9ms/step - loss: 0.0069 - accuracy: 0.9995 - val_loss: 0.0000e+00

In [ ]:
#optimizers = ['Adadelta', 'Adagrad', 'Adam', 'RMSprop', 'SGD']
optimizers = ['Adagrad']

for i in optimizers:
  opt = keras.optimizers.Adagrad(lr=0.1, decay=1e-6)
  model.compile(loss='categorical_crossentropy',optimizer=i,metrics=['accuracy'])
  hist=model.fit(train_X, train_y, batch_size= 64, epochs= 50, validation_data= (test_X, test_y),shuffle=True)

  train_loss = []
  test_loss = []
  train_acc = []
  test_acc = []

  train_loss = hist.history['loss']
  test_loss = hist.history['val_loss']
  train_acc = hist.history['accuracy']
  test_acc = hist.history['val_accuracy']


import pandas as pd
train_acc = pd.DataFrame (train_acc, columns = [i])
test_acc = pd.DataFrame (test_acc, columns = [i])
train_loss = pd.DataFrame (train_loss, columns = [i])
test_loss = pd.DataFrame (test_loss, columns = [i])



train_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_acc.csv', index=False)
test_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_acc.csv', index=False)
train_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_loss.csv', index=False)
test_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_loss.csv', index=False)



/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adagrad.py:77: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adagrad, self).__init__(name, **kwargs)


Epoch 1/50
615/615 [==============================] - 5s 8ms/step - loss: 2.1961 - accuracy: 0.4128 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 2/50
615/615 [==============================] - 5s 7ms/step - loss: 1.9774 - accuracy: 0.4511 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 3/50
615/615 [==============================] - 5s 7ms/step - loss: 1.7977 - accuracy: 0.4914 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 4/50
615/615 [==============================] - 5s 7ms/step - loss: 1.6415 - accuracy: 0.5226 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 5/50
615/615 [==============================] - 5s 7ms/step - loss: 1.5182 - accuracy: 0.5530 - val_loss: 0.0000e+00 - val_accuracy: 7.8933e-05
Epoch 6/50
615/615 [==============================] - 5s 7ms/step - loss: 1.4108 - accuracy: 0.5817 - val_loss: 0.0000e+00 - val_accuracy: 0.0000e+00
Epoch 7/50
615/615 [==============================] - 5s 8ms/step - loss: 1.3139 - accuracy: 0.6118 

In [ ]:
#optimizers = ['Adadelta', 'Adagrad', 'Adam', 'RMSprop', 'SGD']
optimizers = ['Adam']

for i in optimizers:
  opt = keras.optimizers.Adam(lr=0.1, decay=1e-6)
  model.compile(loss='categorical_crossentropy',optimizer=i,metrics=['accuracy'])
  hist=model.fit(train_X, train_y, batch_size= 64, epochs= 50, validation_data= (test_X, test_y),shuffle=True)

  train_loss = []
  test_loss = []
  train_acc = []
  test_acc = []

  train_loss = hist.history['loss']
  test_loss = hist.history['val_loss']
  train_acc = hist.history['accuracy']
  test_acc = hist.history['val_accuracy']


import pandas as pd
train_acc = pd.DataFrame (train_acc, columns = [i])
test_acc = pd.DataFrame (test_acc, columns = [i])
train_loss = pd.DataFrame (train_loss, columns = [i])
test_loss = pd.DataFrame (test_loss, columns = [i])



train_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_acc.csv', index=False)
test_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_acc.csv', index=False)
train_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_loss.csv', index=False)
test_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_loss.csv', index=False)



/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/adam.py:110: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(Adam, self).__init__(name, **kwargs)


Epoch 1/50
615/615 [==============================] - 5s 8ms/step - loss: 0.8822 - accuracy: 0.7404 - val_loss: 0.0000e+00 - val_accuracy: 0.0038
Epoch 2/50
615/615 [==============================] - 5s 8ms/step - loss: 0.1393 - accuracy: 0.9571 - val_loss: 0.0000e+00 - val_accuracy: 0.0040
Epoch 3/50
615/615 [==============================] - 5s 7ms/step - loss: 0.0819 - accuracy: 0.9749 - val_loss: 0.0000e+00 - val_accuracy: 0.0044
Epoch 4/50
615/615 [==============================] - 5s 7ms/step - loss: 0.0540 - accuracy: 0.9835 - val_loss: 0.0000e+00 - val_accuracy: 0.0043
Epoch 5/50
615/615 [==============================] - 5s 9ms/step - loss: 0.0492 - accuracy: 0.9853 - val_loss: 0.0000e+00 - val_accuracy: 0.0046
Epoch 6/50
615/615 [==============================] - 5s 7ms/step - loss: 0.0393 - accuracy: 0.9885 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 7/50
615/615 [==============================] - 5s 8ms/step - loss: 0.0344 - accuracy: 0.9892 - val_loss: 0.0000e+00 -

In [ ]:
#optimizers = ['Adadelta', 'Adagrad', 'Adam', 'RMSprop', 'SGD']
optimizers = ['RMSprop']

for i in optimizers:
  opt = keras.optimizers.RMSprop(lr=0.1, decay=1e-6)
  model.compile(loss='categorical_crossentropy',optimizer=i,metrics=['accuracy'])
  hist=model.fit(train_X, train_y, batch_size= 64, epochs= 50, validation_data= (test_X, test_y),shuffle=True)

  train_loss = []
  test_loss = []
  train_acc = []
  test_acc = []

  train_loss = hist.history['loss']
  test_loss = hist.history['val_loss']
  train_acc = hist.history['accuracy']
  test_acc = hist.history['val_accuracy']


import pandas as pd
train_acc = pd.DataFrame (train_acc, columns = [i])
test_acc = pd.DataFrame (test_acc, columns = [i])
train_loss = pd.DataFrame (train_loss, columns = [i])
test_loss = pd.DataFrame (test_loss, columns = [i])



train_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_acc.csv', index=False)
test_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_acc.csv', index=False)
train_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_loss.csv', index=False)
test_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_loss.csv', index=False)



/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/rmsprop.py:135: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(RMSprop, self).__init__(name, **kwargs)


Epoch 1/50
615/615 [==============================] - 6s 9ms/step - loss: 0.0147 - accuracy: 0.9973 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 2/50
615/615 [==============================] - 5s 8ms/step - loss: 0.0080 - accuracy: 0.9983 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 3/50
615/615 [==============================] - 5s 9ms/step - loss: 0.0074 - accuracy: 0.9987 - val_loss: 0.0000e+00 - val_accuracy: 0.0049
Epoch 4/50
615/615 [==============================] - 5s 9ms/step - loss: 0.0091 - accuracy: 0.9987 - val_loss: 0.0000e+00 - val_accuracy: 0.0049
Epoch 5/50
615/615 [==============================] - 5s 8ms/step - loss: 0.0105 - accuracy: 0.9984 - val_loss: 0.0000e+00 - val_accuracy: 0.0049
Epoch 6/50
615/615 [==============================] - 5s 8ms/step - loss: 0.0092 - accuracy: 0.9988 - val_loss: 0.0000e+00 - val_accuracy: 0.0049
Epoch 7/50
615/615 [==============================] - 5s 8ms/step - loss: 0.0068 - accuracy: 0.9987 - val_loss: 0.0000e+00 -

In [ ]:
#optimizers = ['Adadelta', 'Adagrad', 'Adam', 'RMSprop', 'SGD']
optimizers = ['SGD']

for i in optimizers:
  opt = keras.optimizers.SGD(lr=0.1, decay=1e-6)
  model.compile(loss='categorical_crossentropy',optimizer=i,metrics=['accuracy'])
  hist=model.fit(train_X, train_y, batch_size= 64, epochs= 50, validation_data= (test_X, test_y),shuffle=True)

  train_loss = []
  test_loss = []
  train_acc = []
  test_acc = []

  train_loss = hist.history['loss']
  test_loss = hist.history['val_loss']
  train_acc = hist.history['accuracy']
  test_acc = hist.history['val_accuracy']


import pandas as pd
train_acc = pd.DataFrame (train_acc, columns = [i])
test_acc = pd.DataFrame (test_acc, columns = [i])
train_loss = pd.DataFrame (train_loss, columns = [i])
test_loss = pd.DataFrame (test_loss, columns = [i])



train_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_acc.csv', index=False)
test_acc.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_acc.csv', index=False)
train_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/train_loss.csv', index=False)
test_loss.to_csv('/content/drive/MyDrive/Sreenitha/Projects/Metrocad_ext/opt_graph/' + i +'/test_loss.csv', index=False)



/usr/local/lib/python3.8/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


Epoch 1/50
615/615 [==============================] - 5s 8ms/step - loss: 0.0590 - accuracy: 0.9950 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 2/50
615/615 [==============================] - 5s 7ms/step - loss: 0.0648 - accuracy: 0.9950 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 3/50
615/615 [==============================] - 5s 8ms/step - loss: 0.0242 - accuracy: 0.9977 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 4/50
615/615 [==============================] - 5s 8ms/step - loss: 0.0297 - accuracy: 0.9970 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 5/50
615/615 [==============================] - 5s 7ms/step - loss: 0.0230 - accuracy: 0.9979 - val_loss: 0.0000e+00 - val_accuracy: 0.0048
Epoch 6/50
615/615 [==============================] - 4s 7ms/step - loss: 0.0304 - accuracy: 0.9975 - val_loss: 0.0000e+00 - val_accuracy: 0.0049
Epoch 7/50
615/615 [==============================] - 4s 7ms/step - loss: 0.0195 - accuracy: 0.9982 - val_loss: 0.0000e+00 -